sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t  karthikc2312/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  karthikc2312/docker-react npm run test -- --coverage

